server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      host: 39.101.182.222
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        hostname: 39.101.182.222
        prefer-ip-address: true
        health-check-url: http://${spring.cloud.consul.host}:${spring.cloud.consul.port}



