server:
  port: 80

spring:
  application:
    name: consul-consumer-order
  cloud:
    consul:
      host: 39.101.182.222
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
        health-check-url: http://${spring.cloud.consul.host}:${spring.cloud.consul.port}
